language: go

addons:
    - postgresql: "9.5"

services:
    - postgresql

go:
    - 1.4
    - 1.5
    - 1.6
    - tip

#before_script:
#    - psql -c 'CREATE DATABASE test; CREATE EXTENSION hstore;' -U postgres
