language: go

addons:
    - postgresql: "9.4"

services:
    - postgresql

go:
    - 1.4
    - 1.5
    - 1.6
    - tip

before_script:
    - psql -c 'CREATE DATABASE travis_ci_test; CREATE EXTENSION hstore;' -U postgres
